name: Build web

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web
      - run: |
          cp -R ./build ./builds
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Updated web build"
          git push
